{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spotlight.serviceAccountName" . }}
  labels:
{{ include "spotlight.labels" . | nindent 4 }}
{{- end -}}
